name: "Submit to Web Store"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.15' # Use a specific stable version instead of latest

      # Cache Bun dependencies
      - name: Cache Bun modules
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Change to extension directory
      - name: Change to extension directory
        run: cd extension

      # Install dependencies using Bun
      - name: Install dependencies
        run: cd extension && bun install

      # Build the extension using Bun with increased memory
      - name: Build the extension
        run: cd extension && NODE_OPTIONS=--max_old_space_size=4096 bun run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      # Package the extension using Bun
      - name: Package the extension into a zip artifact
        run: cd extension && bun run package

      # Read the keys.json file
      - name: Read keys file
        id: keys
        run: echo "keys=$(cat extension/keys.json | jq -c)" >> $GITHUB_OUTPUT

      # Publish step using local keys
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ steps.keys.outputs.keys }}
          artifact: extension/build/chrome-mv3-prod.zip
